"""Deterministic clocks and analytical truth shared by hardening tests.

The samples are inputs, never generated by the filter under test. Seeds are
explicit; no wall clock, downloaded weights, or private footage is needed.
"""

from __future__ import annotations

import numpy as np
from numpy.typing import NDArray


def irregular_clock(count: int = 160, *, seed: int = 19) -> NDArray[np.float64]:
    """Positive unequal frame intervals, with a fourfold rate change halfway."""
    intervals = np.random.default_rng(seed).uniform(0.006, 0.012, count - 1)
    intervals[count // 2 :] *= 4
    return np.r_[0.0, np.cumsum(intervals)]


def cubic_motion(t: NDArray[np.float64]) -> tuple[NDArray[np.float64], ...]:
    """Position, velocity, acceleration of 0.2 + 0.3t - 0.4t² + 0.1t³."""
    return 0.2 + 0.3 * t - 0.4 * t**2 + 0.1 * t**3, 0.3 - 0.8 * t + 0.3 * t**2, -0.8 + 0.6 * t
